### ISSUE TITLE
Require sudo and curl

### ISSUE THREAD

**Issue by lucaheise** [versatiles-org/versatiles-generator#5]
Hello,

the 2_prepare_tilemaker.sh script uses _sudo_ and _curl_, both do not ship with default debian installations.

Including it in the setup script should solve the problem, but with _sudo_ I don't know if that can have unpleasant side effects on systems used for other things as well.

**Comment by MichaelKreil** [comment]
Thanks for your tips.
I've been using these scripts to generate the vector tiles for a few months now. But in the meantime, instead of a collection of bash script, I think it would be better to release a Docker container.
I have in mind a Docker container that contains both Tilemaker and Versatiles to work as a tile generator and converter.
Would you find this approach better?

**Comment by lucaheise** [comment]
I myself have used containers to test the previous scripts, so I see no problem putting the whole thing into them.

I don't know yet how I feel about the “instead”, I think the bash scripts should stay there. They show well that the system is actually relatively easy to use and allow self-explored testing.
Since those bash scripts will probably also run inside the containers, it should be possible to keep both without too much effort.
